trigger:
  batch: true
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: github
      name: sundryoss/Sundry.Infra

pool:
  vmImage: ubuntu-latest

stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: jobs/lint.yml@templates
    parameters:
      file: 'main.bicep'